"""fetch-what-say 共用工具:错误码、日志、cookies 解析、srt/txt、schema。

不依赖 esflow,节点与 run.py 共用。HTML 渲染在 nodes/export_html.py。
"""

from __future__ import annotations

import json
import re
import shutil
import sys
from pathlib import Path
from urllib.parse import urlparse


SCHEMA_VERSION = "1.0.0"
# 0 ok / 1 runtime / 2 to_agent / 3 validation / 4 auth
EXIT_OK, EXIT_RUNTIME, EXIT_TO_AGENT, EXIT_VALIDATION, EXIT_AUTH = 0, 1, 2, 3, 4
DEFAULT_WHISPER_MODEL = "mlx-community/whisper-large-v3-turbo"
DEFAULT_OUTPUT_DIR = Path.home() / "Downloads" / "fetch-what-say"
DEFAULT_COOKIES_DIR = DEFAULT_OUTPUT_DIR / "cookies"


class CliError(Exception):
    """带稳定错误码的 CLI 异常。"""

    def __init__(self, code, message, exit_code=EXIT_RUNTIME, retryable=False):
        super().__init__(message)
        self.code = code
        self.message = message
        self.exit_code = exit_code
        self.retryable = retryable


def log(message):
    print(message, file=sys.stderr, flush=True)


def safe_id(value):
    return re.sub(r"\W+", "_", value).strip("_")[-80:] or "media"


def resolve_input(value):
    """把 CLI input 参数解析成 (kind, value)。"""
    value = value.strip()
    path = Path(value).expanduser()
    if path.is_file():
        return "file", path
    if value.startswith(("http://", "https://")):
        return "url", value
    raise CliError("validation_error", f"必须传入完整 URL 或本地文件：{value}", EXIT_VALIDATION)


# —— cookies ——

def copy_cookies_to_store(source_path):
    """将用户提供的 cookies 复制到统一存储目录,便于后续复用。"""
    DEFAULT_COOKIES_DIR.mkdir(parents=True, exist_ok=True)
    target = DEFAULT_COOKIES_DIR / source_path.name
    if not target.exists() or source_path.stat().st_mtime > target.stat().st_mtime:
        shutil.copy2(source_path, target)
        log(f"[cookies] 已复制到 {target}")
    return target


def stored_cookies():
    if not DEFAULT_COOKIES_DIR.exists():
        return []
    return [path for path in DEFAULT_COOKIES_DIR.glob("*.txt") if path.is_file()]


def cookie_domain_tokens(url):
    hostname = urlparse(url).hostname or ""
    return [part for part in hostname.lower().split(".") if part and part not in {"www", "com", "cn", "net", "org"}]


def resolve_cookies(explicit_path, resolved_input=None):
    """显式 cookies 优先;否则按 URL 域名匹配默认存储目录。本地文件无需 cookies。"""
    if explicit_path:
        path = Path(explicit_path).expanduser()
        if not path.exists():
            raise CliError("auth_error", f"cookies 文件不存在：{path}", EXIT_AUTH)
        copy_cookies_to_store(path)
        return path
    if not isinstance(resolved_input, str) or not resolved_input.startswith(("http://", "https://")):
        return None
    tokens = cookie_domain_tokens(resolved_input)
    matches = [
        path for path in stored_cookies()
        if any(token in path.stem.lower() for token in tokens)
    ]
    if not matches:
        return None
    selected = max(matches, key=lambda path: path.stat().st_mtime)
    log(f"[cookies] 使用默认 cookies：{selected}")
    return selected


# —— srt/txt ——

def srt_timestamp(seconds):
    total_ms = max(0, int(round(float(seconds) * 1000)))
    total_seconds, ms = divmod(total_ms, 1000)
    minutes_total, second = divmod(total_seconds, 60)
    hour, minute = divmod(minutes_total, 60)
    return f"{hour:02d}:{minute:02d}:{second:02d},{ms:03d}"


def write_srt(segments, subtitle_path):
    lines = []
    index = 1
    for segment in segments:
        text = re.sub(r"\s+", " ", segment.get("text", "")).strip()
        if not text:
            continue
        lines.extend([
            str(index),
            f"{srt_timestamp(segment['start'])} --> {srt_timestamp(segment['end'])}",
            text,
            "",
        ])
        index += 1
    subtitle_path.write_text("\n".join(lines), encoding="utf-8")


def is_tail_noise(text):
    return not re.search(r"[\u4e00-\u9fffA-Za-z0-9]", text)


def write_txt_from_srt(subtitle_path, transcript_path):
    lines = []
    blocks = re.split(r"\n\s*\n", subtitle_path.read_text(encoding="utf-8").strip())
    for block in blocks:
        parts = [line.strip() for line in block.splitlines() if line.strip()]
        payload = [line for line in parts if not line.isdigit() and "-->" not in line]
        text = " ".join(payload)
        if text and not is_tail_noise(text):
            lines.append(text)
    transcript_path.write_text("\n".join(lines) + "\n", encoding="utf-8")


# —— 输出契约 ——

def schema():
    return {
        "ok": "boolean",
        "data": {
            "video": "string path",
            "cached": "boolean",
            "transcripts": "object, default unless --no-transcribe",
            "summary": "summary.txt path, generated by Agent",
            "dry_run": "boolean",
            "plan": "object",
        },
        "error": {"code": "string", "message": "string", "retryable": "boolean"},
        "exit_codes": {"0": "ok", "1": "runtime", "2": "to_agent", "3": "validation", "4": "auth"},
    }


def output_schema():
    print(json.dumps(schema(), ensure_ascii=False, indent=2))
